#include "ConfigCreator.h"

#include <fstream>
#include <iostream>
#include <set>
#include <tuple>
#include <vector>

using namespace std;

ConfigCreator::ConfigCreator(const std::string& filename) : filename_(filename), config_({
	{"FileOrigin", "This file is automatically generated by ControlHardwareConfigFileCreator.cpp. Do not edit it manually."},
	{"ConfigurationName", "AQuRA"},
	{"PCSequenceBufferSize", 134217728},
	{"LineFrequency", 50},
	{"Sequencers", json::array()},
	{"Rack", json::array()},
	{"AnalogOutBoards16bit", json::array()},
	{"DigitalOutBoards", json::array()},
	{"SerialPortBoards", json::array()},
	{"DDSAD9854Boards", json::array()},
	{"DDSAD9858Boards", json::array()},
	{"DDSAD9959Boards", json::array()},
	{"AnalogInBoards12bit", json::array()}
}) {
}

void ConfigCreator::AddOptionalHardwareFields(json& entry,
	const optional<string>& Model,
	const optional<string>& SN,
	const optional<int>& RackNr,
	const optional<int>& SlotNr) {
	if (Model.has_value()) {
		entry["Model"] = *Model;
	}
	if (SN.has_value()) {
		entry["SN"] = *SN;
	}
	if (RackNr.has_value()) {
		entry["RackNr"] = *RackNr;
	}
	if (SlotNr.has_value()) {
		entry["SlotNr"] = *SlotNr;
	}
}

void ConfigCreator::RegisterSequencer(int Id, const std::string& Type, const std::string& IP, int Port,
	bool Master, int StartDelay, int ClockFrequencyinMHz, int FPGAClockToBusClockRatio, bool UseExternalClock,
	bool UseStrobeGenerator, bool UseEdgeTriggeredLatches, bool Connect, bool DebugOn, const optional<string>& Model,
	const optional<string>& SN, const optional<int>& RackNr, const optional<int>& SlotNr) {
	json entry = {
		{"Id", Id},
		{"Type", Type},
		{"IP", IP},
		{"Port", Port},
		{"Master", Master},
		{"StartDelay", StartDelay},
		{"ClockFrequencyinMHz", ClockFrequencyinMHz},
		{"FPGAClockToBusClockRatio", FPGAClockToBusClockRatio},
		{"UseExternalClock", UseExternalClock},
		{"UseStrobeGenerator", UseStrobeGenerator},
		{"UseEdgeTriggeredLatches", UseEdgeTriggeredLatches},
		{"Connect", Connect},
		{"DebugOn", DebugOn}
	};
	AddOptionalHardwareFields(entry, Model, SN, RackNr, SlotNr);
	config_["Sequencers"].push_back(entry);
}

void ConfigCreator::RegisterAnalogOutBoard16bit(int Sequencer, int StartAddress, int NumberChannels,
	bool Signed, double MinVoltage, double MaxVoltage, const optional<string>& Model,
	const optional<string>& SN, const optional<int>& RackNr, const optional<int>& SlotNr) {
	json entry = {
		{"Sequencer", Sequencer},
		{"StartAddress", StartAddress},
		{"NumberChannels", NumberChannels},
		{"Signed", Signed},
		{"MinVoltage", MinVoltage},
		{"MaxVoltage", MaxVoltage}
	};
	AddOptionalHardwareFields(entry, Model, SN, RackNr, SlotNr);
	config_["AnalogOutBoards16bit"].push_back(entry);
}

void ConfigCreator::RegisterDigitalOutBoard(int Sequencer, int Address, int NumberChannels,
	const optional<string>& Model, const optional<string>& SN,
	const optional<int>& RackNr, const optional<int>& SlotNr) {
	json entry = {
		{"Sequencer", Sequencer},
		{"Address", Address},
		{"NumberChannels", NumberChannels}
	};
	AddOptionalHardwareFields(entry, Model, SN, RackNr, SlotNr);
	config_["DigitalOutBoards"].push_back(entry);
}

void ConfigCreator::RegisterSerialPortBoard(int Sequencer, int Address, int RackNr, int SlotNr,
	const optional<string>& Model, const optional<string>& SN) {
	json entry = {
		{"Sequencer", Sequencer},
		{"Address", Address},
		{"RackNr", RackNr},
		{"SlotNr", SlotNr}
	};
	AddOptionalHardwareFields(entry, Model, SN);
	config_["SerialPortBoards"].push_back(entry);
}

void ConfigCreator::RegisterDDSAD9854Board(int Version, int Sequencer, int Address,
	double ExternalClockFrequencyinMHz, int PLLReferenceMultiplier, double FrequencyMultiplier,
	const optional<string>& Model, const optional<string>& SN,
	const optional<int>& RackNr, const optional<int>& SlotNr) {
	json entry = {
		{"Version", Version},
		{"Sequencer", Sequencer},
		{"Address", Address},
		{"ExternalClockFrequencyinMHz", ExternalClockFrequencyinMHz},
		{"PLLReferenceMultiplier", PLLReferenceMultiplier},
		{"FrequencyMultiplier", FrequencyMultiplier}
	};
	AddOptionalHardwareFields(entry, Model, SN, RackNr, SlotNr);
	config_["DDSAD9854Boards"].push_back(entry);
}

void ConfigCreator::RegisterDDSAD9858Board(int Sequencer, int Address, double ClockFrequencyinMHz,
	double FrequencyMultiplier, const optional<string>& Model, const optional<string>& SN,
	const optional<int>& RackNr, const optional<int>& SlotNr) {
	json entry = {
		{"Sequencer", Sequencer},
		{"Address", Address},
		{"ClockFrequencyinMHz", ClockFrequencyinMHz},
		{"FrequencyMultiplier", FrequencyMultiplier}
	};
	AddOptionalHardwareFields(entry, Model, SN, RackNr, SlotNr);
	config_["DDSAD9858Boards"].push_back(entry);
}

void ConfigCreator::RegisterDDSAD9959Board(int Sequencer, int Address, double ClockFrequencyinMHz,
	double FrequencyMultiplier, bool AD9958, const optional<string>& Model, const optional<string>& SN,
	const optional<int>& RackNr, const optional<int>& SlotNr) {
	json entry = {
		{"Sequencer", Sequencer},
		{"Address", Address},
		{"ClockFrequencyinMHz", ClockFrequencyinMHz},
		{"FrequencyMultiplier", FrequencyMultiplier},
		{"AD9958", (AD9958) ? 1 : 0}
	};
	AddOptionalHardwareFields(entry, Model, SN, RackNr, SlotNr);
	config_["DDSAD9959Boards"].push_back(entry);
}

void ConfigCreator::RegisterAnalogInBoard12bit(int Sequencer, int Address, int NumberChannels,
	double MinVoltage, double MaxVoltage, const optional<string>& Model,
	const optional<string>& SN, const optional<int>& RackNr, const optional<int>& SlotNr) {
	json entry = {
		{"Sequencer", Sequencer},
		{"ChipSelect", Address},
		{"NumberChannels", NumberChannels},
		{"MinVoltage", MinVoltage},
		{"MaxVoltage", MaxVoltage}
	};
	AddOptionalHardwareFields(entry, Model, SN, RackNr, SlotNr);
	config_["AnalogInBoards12bit"].push_back(entry);
}

void ConfigCreator::RegisterRackEntry(const json& entry) {
	config_["Rack"].push_back(entry);
}

bool ConfigCreator::Save() const {
	set<tuple<int, int>> used_addresses;
	vector<string> errors;

	auto check_and_add = [&](int sequencer, int address, int span, const string& name) {
		if (address % span != 0) {
			errors.push_back(name + " at address " + to_string(address) +
				" should start at a multiple of " + to_string(span) + ".");
		}
		for (int offset = 0; offset < span; ++offset) {
			const int current_address = address + offset;
			const auto key = make_tuple(sequencer, current_address);
			if (current_address < 1 || current_address > 251) {
				errors.push_back(name + " uses address " + to_string(current_address) +
					", which is out of range [1, 251].");
			}
			else if (used_addresses.contains(key)) {
				errors.push_back("Conflict: " + name + " at [" + to_string(sequencer) + ", " +
					to_string(current_address) + "] already in use.");
			}
			used_addresses.insert(key);
		}
	};

	for (const auto& entry : config_["AnalogOutBoards16bit"]) {
		check_and_add(entry["Sequencer"], entry["StartAddress"], entry["NumberChannels"], "AnalogOutBoard16bit");
	}
	for (const auto& entry : config_["DigitalOutBoards"]) {
		check_and_add(entry["Sequencer"], entry["Address"], 1, "DigitalOutBoard");
	}
	for (const auto& entry : config_["SerialPortBoards"]) {
		check_and_add(entry["Sequencer"], entry["Address"], 1, "SerialPortBoard");
	}
	for (const auto& entry : config_["DDSAD9854Boards"]) {
		check_and_add(entry["Sequencer"], entry["Address"], 4, "DDSAD9854Board");
	}
	for (const auto& entry : config_["DDSAD9858Boards"]) {
		check_and_add(entry["Sequencer"], entry["Address"], 4, "DDSAD9858Board");
	}
	for (const auto& entry : config_["DDSAD9959Boards"]) {
		check_and_add(entry["Sequencer"], entry["Address"], 1, "DDSAD9959Board");
	}
	for (const auto& entry : config_["AnalogInBoards12bit"]) {
		check_and_add(entry["Sequencer"], entry["ChipSelect"], 1, "AnalogInBoard12bit");
	}

	if (!errors.empty()) {
		cout << "Design rule check failed:" << endl;
		for (const auto& error : errors) {
			cout << "- " << error << endl;
		}
		cout << "\nPlease fix the above issues in your RegisterXXX calls.\n" << endl;
		return false;
	}

	ofstream file(filename_);
	if (!file.is_open()) {
		cout << "\nFailed to open JSON file '" << filename_ << "' for writing.\n" << endl;
		return false;
	}

	file << config_.dump(2);
	cout << "\nConfiguration is valid. JSON file '" << filename_ << "' created successfully.\n" << endl;
	return true;
}
